spring: 
  profiles: 
  active: 
  - dev
---
spring: 
  profiles:dev
  application: 
    name:spring-cloud-config-dev
---
spring: 
 profiles:test
 application:
  name:spring-cloud-config-test
# 保存为UTF8格式
